POST http://localhost:3000/longestWord/The%20quick%20brown%20fox%20jumps%20over%20the%20lazy%20dog
content-type: application/json
{
 "longestWord" : "quick",
}
###
GET http://localhost:3000/shortestWord/The%20quick%20brown%20fox%20jumps%20over%20the%20lazy%20dog
content-type: application/json
{
 "shortestWord" : "the",
}
###
GET http://localhost:3000/sum/The%20quick%20brown%20fox%20jumps%20over%20the%20lazy%20dog
content-type: application/json
{
 "sum" : 23
}
###
POST http://localhost:3000/totalPhoneBill/:calls or Sms
Content-Type: application/json
{
    "bill": "call,sms,call"
}
###
GET http://localhost:3000/totalPhoneBill/:calls or Sms
Content-Type: application/json
{
 "call" : 2.75,
 "sms": 0.65
}
###
GET  http://localhost:3000/enoughAirtime/callOrSms
Content-Type: application/json
{
   "usage": "call,sms,call"
   "available" : 54
}